### ISSUE TITLE
Porting some new TensorFlow models

### ISSUE THREAD

**Issue by GlebSBrykin** [reiinakano/fast-style-transfer-deeplearnjs#16]
Hello! I really liked Your project, it helped me a lot. I would like to ask you to port 4 new styles from this repository: [https://github.com/hzy46/fast-neural-style-tensorflow](https://github.com/hzy46/fast-neural-style-tensorflow). Everything on TensorFlow, and I think for You it will not be difficult. Unfortunately, I do not have the opportunity to do it myself.

**Comment by reiinakano** [comment]
Sorry, the trained weights from that repository do not use the same neural network as this one. You would need to do your own training for those styles as documented in https://github.com/reiinakano/fast-style-transfer-deeplearnjs#adding-your-own-styles

Unfortunately, I can't do it myself as I do not have access to a powerful GPU.

**Comment by GlebSBrykin** [comment]
It turns out, there already trained network for van Gogh? Can you port models from Keras or Torch?
