### ISSUE TITLE
mobile browser 

### ISSUE THREAD

**Issue by weigq** [reiinakano/fast-style-transfer-deeplearnjs#2]
can this demo run on mobile browser?

**Comment by reiinakano** [comment]
Hi @weigq, I don't think so. You would have to get the authors of deeplearnjs to really get details of when mobile support will be available, but either way, this demo wasn't built for mobile.

**Comment by weigq** [comment]
@reiinakano , thank you for explanation. 
It seems that deeplearn.js can support chrome now.
I`ll closed this issue
