### ISSUE TITLE
404 on bundle.js

### ISSUE THREAD

**Issue by superMDguy** [reiinakano/fast-style-transfer-deeplearnjs#5]
I went to https://reiinakano.github.io/fast-style-transfer-deeplearnjs/,  but it didn't load at all.  I checked the console, and there was a 404 on https://reiinakano.github.io/fast-style-transfer-deeplearnjs/bundle.js.

**Comment by reiinakano** [comment]
Works now.. I just tried to hotfix something into production, and screwed things up.. Haha, I learned my lesson for sure!

**Comment by superMDguy** [comment]
Great, thanks!
