### ISSUE TITLE
DemoSite Error - ReferenceError: dialogPolyfill is not defined

### ISSUE THREAD

**Issue by RexMorgan** [reiinakano/fast-style-transfer-deeplearnjs#6]
Getting this error on Firefox 57 (beta) and Chrome 61 on Windows 10.

All of the requests seem to work properly, with adblockers disabled.

All I see is a white page w/ the github logo in the corner.

![image](https://user-images.githubusercontent.com/178752/31085830-cfafd738-a75d-11e7-94fe-9f1ec789608d.png)

![image](https://user-images.githubusercontent.com/178752/31085689-81e935e4-a75d-11e7-8f0d-b39b48feb095.png)

**Comment by reiinakano** [comment]
Okay, looked a bit into this and this piece of code is only run if an unsupported browser is detected, which is one of three cases: mobile or Safari or a non-WebGL enabled browser.

I guess if you're not on mobile or Safari, then your browser doesn't support WebGL and you wouldn't be able to run it either. Sorry!

You can see the warnings on the console confirming your browser does not support WebGL.

**Comment by RexMorgan** [comment]
@reiinakano thanks. I enabled webgl in firefox and the page loads, now.

Unfortunately the site doesn't work, and I get some webgl errors. I'm assuming that's because webgl was disabled by default for a reason :)

![image](https://user-images.githubusercontent.com/178752/31086882-afce1472-a760-11e7-8715-3588eabb391c.png)

For others, I set `webgl.force-enabled` to true in `about:config` to enable webgl.

**Comment by reiinakano** [comment]
You might want to try running the official deeplearn JS demos http://deeplearnjs.org/index.html#demos and see if the same errors pop up.

If they do, then you'll get a better answer by filing an issue there. I am honestly clueless about the internals of the library. I am a mere user, haha. :)

**Comment by reiinakano** [comment]
This is now fixed in the newest version. You should see a proper error message now if your device is unsupported.
