### ISSUE TITLE
'Repository has exceeded LFS data quota' - LFS really needed?

### ISSUE THREAD

**Issue by maltebaumann** [reiinakano/fast-style-transfer-deeplearnjs#8]
Hey, I really like the project and would like to help with further improvements (e.g. adding the optimizations made by Dumoulin et al.), but it seems like this repository has exceeded it's LFS quota:

```
Error downloading object: src/ckpts/la_muse/Variable (5fb0a17): Smudge error: Error downloading src/ckpts/la_muse/Variable 
(5fb0a170666f9305d6b2640156b025af45a1c118cefb5da3708c1820a2613c7b): batch response: This repository is over its data quota. Purchase more data packs to restore access.
```

Is it really necessary to use LFS for the example images and checkpoints? As far as I know, a single checkpoint should weigh in at ~7MB, so I don't really see the need for LFS to store 42MB of checkpoints and a few images. I would create a pull request that adds the actual files, but I'm currently unable to clone the repository due to the error above.

Thanks for the great work!

**Comment by reiinakano** [comment]
Hey there, thanks for taking an interest in this project. You're right, I've been thinking about moving the files out of LFS but haven't gotten to it yet. I'll update this issue when I get to it within a few days perhaps.

**Comment by reiinakano** [comment]
Done!
